#ifndef CONFIG_KEYS_H
#define CONFIG_KEYS_H

#define KEY_CONFIG                "config"
#define KEY_MODULES               "plugins"
#define KEY_SENSOR                "sensor"
#define KEY_MOTOR                 "motor"
#define KEY_ACTUATOR              "actuator"
#define KEY_ROBOT                 "robot"
#define KEY_SIGNAL_IO             "signal_io"
#define KEY_ROBOT_CONTROL         "robot_control"
#define KEY_CONTROLLER            "controller"
#define KEY_TIME_STEP             "time_step"
#define KEY_INPUT_INTERFACE       "input_interface"
#define KEY_OUTPUT_INTERFACE      "output_interface"
#define KEY_TYPE                  "type"
#define KEY_CHANNEL               "channel"
#define KEY_VARIABLE              "variable_type"
#define KEY_DEVIATION             "deviation"
#define KEY_MULTIPLIER            "multiplier"
#define KEY_DIVISOR               "divisor"
#define KEY_REFERENCE             "reference"
#define KEY_INPUT_GAIN            "input_gain"
#define KEY_OUTPUT_GAIN           "output_gain"
#define KEY_DIFFERENTIAL_GAIN     "differential_gain"
#define KEY_SIGNAL_PROCESSING     "signal_processing"
#define KEY_MIN_FREQUENCY         "min_frequency"
#define KEY_MAX_FREQUENCY         "max_frequency"
#define KEY_RECTIFIED             "rectified"
#define KEY_NORMALIZED            "normalized"
#define KEY_LOG                   "log"
#define KEY_FILE                  "file"
#define KEY_PRECISION             "precision"

#endif // CONFIG_KEYS_H
